Problem 2  
Dataset: olympics\_top20.csv

    ## # A tibble: 1 × 1
    ##     q95
    ##   <dbl>
    ## 1   183

So, here the 95th percentile of heights for female competitors is 183.

    ## # A tibble: 132 × 2
    ##    event                                 height_sd
    ##    <chr>                                     <dbl>
    ##  1 Rowing Women's Coxed Fours                10.9 
    ##  2 Basketball Women's Basketball              9.70
    ##  3 Rowing Women's Coxed Quadruple Sculls      9.25
    ##  4 Rowing Women's Coxed Eights                8.74
    ##  5 Swimming Women's 100 metres Butterfly      8.13
    ##  6 Volleyball Women's Volleyball              8.10
    ##  7 Gymnastics Women's Uneven Bars             8.02
    ##  8 Shooting Women's Double Trap               7.83
    ##  9 Cycling Women's Keirin                     7.76
    ## 10 Swimming Women's 400 metres Freestyle      7.62
    ## # … with 122 more rows

The singles event where we can see the greatest variability is in the
event Rowing Women’s Coxed fours which has the standard deviation on
10.9.

![](Data-Mining-Assignment-1-Problem-2_files/figure-markdown_strict/unnamed-chunk-6-1.png)
We can observe from the above graph that males started playing earlier
than females.And average age for swimmers have gone up because of that.
One possible reason could be that females were not physically fit at
that time or they were involved in the world war like situation.
